import logging
from typing import Literal

from pydantic import BaseModel, Field
from langsmith import traceable

from src.states.blogstate import AgentState, Task
from src.errors.exceptions import (
    AgentFlowError,
    InvalidWorkflowError,
    PlannerFailure,
)
from src.utils.loggers import get_logger, log_event


logger = get_logger(__name__)


class PlannedTask(BaseModel):
    """
    Structured task produced by the workflow planner.

    Supported task types:
        research
        blog
        email
    """

    id: str = Field(..., min_length=1)
    type: Literal["research", "blog", "email"]
    description: str = Field(..., min_length=1, max_length=200)
    depends_on: list[str]
    use_blog: bool

    # id: str = Field(
    #     ...,
    #     min_length=1,
    #     description="Unique task identifier such as task_1.",
    # )

    # type: Literal[
    #     "research",
    #     "blog",
    #     "email",
    # ] = Field(
    #     ...,
    #     description="Worker responsible for executing the task.",
    # )

    # description: str = Field(
    #     ...,
    #     min_length=1,
    #     description="Specific action performed by the task.",
    # )

    # depends_on: list[str] = Field(
    #     ...,
    #     description=(
    #         "Task IDs that must complete before this task. "
    #         "Use [] when there are no dependencies."
    #     ),
    # )

    # use_blog: bool = Field(
    #     ...,
    #     description=(
    #         "True only when an email task consumes the output "
    #         "of a blog task. Otherwise false."
    #     ),
    # )


class WorkflowPlan(BaseModel):
    """
    Complete dependency graph generated by the planner.
    """

    tasks: list[PlannedTask] = Field(
        ...,
        min_length=1,
        description="Executable workflow tasks.",
    )


class WorkflowPlanner:

    def __init__(
        self,
        llm,
    ):
        self.llm = llm

        self.structured_llm = llm.with_structured_output(
            WorkflowPlan
        )

        log_event(
            logger,
            level=logging.INFO,
            event="workflow_planner_initialized",
        )

    def validate_plan(
        self,
        tasks: list[PlannedTask],
    ) -> None:
        """
        Validate planner output.

        Supported dependency patterns:

            research → blog → email

        Also supported:

            blog → email

            research → blog

            independent research

            independent blog

            independent email

            research + independent email
        """

        if not tasks:
            raise ValueError(
                "Planner returned an empty workflow."
            )

       

        task_ids = [
            task.id.strip()
            for task in tasks
        ]

        if len(set(task_ids)) != len(task_ids):
            raise InvalidWorkflowError(
    context={
        "operation": "validate_plan",
        "reason": "duplicate_task_ids",
    },
)

        task_map = {
            task.id.strip(): task
            for task in tasks
        }

      

        for task in tasks:

            task_id = task.id.strip()

            if not task_id:
                raise ValueError(
                    "Planner produced an empty task ID."
                )

            if not task.description.strip():
                raise ValueError(
                    f"Task '{task_id}' has an empty description."
                )

            dependency_ids = [
                dependency_id.strip()
                for dependency_id in task.depends_on
            ]

           

            if task_id in dependency_ids:
                raise ValueError(
                    f"Task '{task_id}' cannot depend on itself."
                )

         

            for dependency_id in dependency_ids:

                if dependency_id not in task_map:
                    raise ValueError(
                        f"Task '{task_id}' depends on "
                        f"unknown task '{dependency_id}'."
                    )

         

            if task.type == "research":

                if task.use_blog:
                    raise ValueError(
                        f"Research task '{task_id}' "
                        "cannot have use_blog=True."
                    )

                if dependency_ids:
                    raise ValueError(
                        f"Research task '{task_id}' "
                        "cannot depend on another task."
                    )

          
            elif task.type == "blog":

                if task.use_blog:
                    raise ValueError(
                        f"Blog task '{task_id}' "
                        "cannot have use_blog=True."
                    )

                for dependency_id in dependency_ids:

                    dependency_task = task_map[
                        dependency_id
                    ]

                    if dependency_task.type != "research":
                        raise ValueError(
                            f"Blog task '{task_id}' "
                            "can only depend on research tasks."
                        )

        

            elif task.type == "email":

                blog_dependencies = [
                    dependency_id
                    for dependency_id in dependency_ids
                    if task_map[
                        dependency_id
                    ].type == "blog"
                ]

                research_dependencies = [
                    dependency_id
                    for dependency_id in dependency_ids
                    if task_map[
                        dependency_id
                    ].type == "research"
                ]

                # Email consuming generated blog
                if task.use_blog:

                    if not blog_dependencies:
                        raise ValueError(
                            f"Email task '{task_id}' "
                            "has use_blog=True but does not "
                            "depend on a blog task."
                        )

                # Independent email
                else:

                    if blog_dependencies:
                        raise ValueError(
                            f"Email task '{task_id}' "
                            "has use_blog=False but depends "
                            "on a blog task."
                        )

                    if research_dependencies:
                        raise ValueError(
                            f"Email task '{task_id}' "
                            "cannot directly depend on research."
                        )

            else:
                raise ValueError(
                    f"Unsupported task type '{task.type}'."
                )

    def validate_no_cycles(
        self,
        tasks: list[PlannedTask],
    ) -> None:
        """
        Detect circular dependencies using DFS.
        """

        dependency_graph = {
            task.id.strip(): [
                dependency_id.strip()
                for dependency_id in task.depends_on
            ]
            for task in tasks
        }

        visiting: set[str] = set()
        visited: set[str] = set()

        def visit(
            task_id: str,
        ) -> None:

            if task_id in visiting:
                raise InvalidWorkflowError(
    context={
        "operation": "validate_no_cycles",
        "reason": "circular_dependency",
        "task_id": task_id,
    },
)

            if task_id in visited:
                return

            visiting.add(task_id)

            for dependency_id in dependency_graph.get(
                task_id,
                [],
            ):
                visit(dependency_id)

            visiting.remove(task_id)
            visited.add(task_id)

        for task_id in dependency_graph:
            visit(task_id)


    @traceable(
        name="workflow_planner",
        run_type="chain",
    )
    async def plan(
        self,
        state: AgentState,
    ):
        """
        Convert the user's natural-language request into
        an executable dependency graph.
        """

        query = state.get("query")

        if not query:
            raise InvalidWorkflowError(
        context={
            "operation": "plan",
            "reason": "query_missing",
        },
    )

       

        prompt = f"""

You are a workflow planner.

Create the smallest executable workflow for the user's request.

Allowed task types:
research, blog, email

Rules:
1. IDs must be task_1, task_2, ... in order.
2. Research: depends_on=[], use_blog=false.
3. Blog: may depend only on research; use_blog=false.
4. Independent email: depends_on=[], use_blog=false.
5. Email sending a generated blog: depends_on=[blog task ID], use_blog=true.
6. Email cannot depend directly on research.
7. Do not create unnecessary tasks.
8. Keep independent actions independent.
9. Keep task descriptions concise.

Examples:

Research + blog:
research(task_1) -> []
blog(task_2) -> ["task_1"]

Blog + email:
blog(task_1) -> []
email(task_2) -> ["task_1"], use_blog=true

User request:

User request:

{query}
"""

       
        try:
          result = await self.structured_llm.ainvoke(
            prompt
          )

        except AgentFlowError:
          raise

        except Exception as exc:
              logger.exception(
                  "Workflow planner failed",
                   extra={
              "event": "workflow_planner_failed",
              },
              )

              raise PlannerFailure(
                  context={
                   "operation": "structured_planning",
                   },
              ) from exc
        
        self.validate_plan(
            result.tasks
        )

        self.validate_no_cycles(
            result.tasks
        )

      

        runtime_tasks: list[Task] = []

        for planned_task in result.tasks:

            runtime_tasks.append(
                Task(
                    id=planned_task.id.strip(),

                    type=planned_task.type,

                    description=(
                        planned_task.description.strip()
                    ),

                    depends_on=[
                        dependency_id.strip()
                        for dependency_id
                        in planned_task.depends_on
                    ],

                    use_blog=planned_task.use_blog,

                    status="pending",

                    result=None,
                )
            )

     
        log_event(
            logger,
            level=logging.INFO,
            event="workflow_plan_created",
            task_count=len(runtime_tasks),
            tasks=[
                {
                    "id": task.id,
                    "type": task.type,
                    "depends_on": task.depends_on,
                    "use_blog": task.use_blog,
                }
                for task in runtime_tasks
            ],
        )

      

        return {
            "tasks": runtime_tasks,

            "current_task": None,

            "completed_tasks": [],

            "running_tasks": [],

            "task_results": {},

            "task_result": None,

            "approval": None,

            "research": None,

            "blog": None,

            "email": None,

            "workflow_results": [],

            "response": "",

            "tool_result": None,
        }