from enum import StrEnum


class ErrorCode(StrEnum):
    LLM_FAILURE = "LLM_FAILURE"
    RESEARCH_FAILED = "RESEARCH_FAILED"
    GMAIL_FAILURE = "GMAIL_FAILURE"
    DATABASE_FAILURE = "DATABASE_FAILURE"

    PLANNER_FAILURE = "PLANNER_FAILURE"
    INVALID_WORKFLOW = "INVALID_WORKFLOW"
    EXECUTOR_FAILURE = "EXECUTOR_FAILURE"
    UNKNOWN_TASK = "UNKNOWN_TASK"
    WORKFLOW_DEADLOCK = "WORKFLOW_DEADLOCK"

    GUARDRAIL_REJECTION = "GUARDRAIL_REJECTION"
    GUARDRAIL_FAILURE = "GUARDRAIL_FAILURE"

    HITL_TIMEOUT = "HITL_TIMEOUT"

    INVALID_REQUEST = "INVALID_REQUEST"
    INTERNAL_ERROR = "INTERNAL_ERROR"