# mypy: ignore-errors

import logging
from time import perf_counter

from pydantic import BaseModel, Field

from src.states.blogstate import AgentState
from src.tools.research_tool import ResearchTool
from src.utils.loggers import (
    get_logger,
    log_event,
)


logger = get_logger(__name__)




# Tavily search results.
MAX_RESEARCH_SOURCES = 5

# Only the best sources are sent to the synthesis LLM.
MAX_LLM_SOURCES = 2

# Maximum characters from each source sent to the LLM.
MAX_SOURCE_CONTENT_CHARS = 1000

# Prevent extremely large task descriptions from reaching
# the synthesis model.
MAX_QUERY_CHARS = 400

# Keep the generated research artifact compact.
MAX_KEY_FINDINGS = 3

# Keep the synthesis concise.
MAX_SUMMARY_WORDS = 70

# Keep individual findings short.
MAX_FINDING_WORDS = 18



class ResearchSynthesis(BaseModel):
    """
    Compact research artifact generated by the LLM.

    Sources are intentionally excluded.

    Tavily sources are used internally as evidence during
    research synthesis and are NOT passed downstream.
    """

    summary: str = Field(
        ...,
        min_length=1,
        description="Concise factual research summary.",
    )

    key_findings: list[str] = Field(
        ...,
        min_length=1,
        max_length=MAX_KEY_FINDINGS,
        description="Important factual findings.",
    )




class ResearchNode:

    def __init__(
        self,
        llm,
    ):

        self.llm = llm

        self.research_tool = ResearchTool()

        self.structured_llm = (
            llm.with_structured_output(
                ResearchSynthesis
            )
        )

        log_event(
            logger,
            level=logging.INFO,
            event="research_node_initialized",
            status="success",
        )




    @staticmethod
    def get_current_task(
        state: AgentState,
    ):

        task_id = state.get(
            "current_task"
        )

        if not task_id:
            return None

        for task in state.get(
            "tasks",
            [],
        ):

            if task.id == task_id:
                return task

        return None





    @staticmethod
    def _build_llm_context(
        sources,
    ):

        context_parts = []

        for index, source in enumerate(
            sources,
            start=1,
        ):

            title = str(
                source.get(
                    "title",
                    "",
                )
            ).strip()

            content = str(
                source.get(
                    "content",
                    "",
                )
            ).strip()

            # Keep only a small evidence window.
            content = content[
                :MAX_SOURCE_CONTENT_CHARS
            ]

            if not content:
                continue

            context_parts.append(
                f"SOURCE {index}\n"
                f"{title}\n"
                f"{content}"
            )

        return "\n\n".join(
            context_parts
        )



   

    @staticmethod
    def _normalize_findings(
        findings,
    ):

        normalized = []

        for finding in findings:

            finding = str(
                finding
            ).strip()

            if not finding:
                continue

            if finding in normalized:
                continue

            normalized.append(
                finding
            )

            if len(normalized) >= (
                MAX_KEY_FINDINGS
            ):
                break

        return normalized



   

    async def research(
        self,
        state: AgentState,
    ):

        request_id = state.get(
            "request_id"
        )

        current_task = self.get_current_task(
            state
        )


        

        if current_task is None:

            raise ValueError(
                "No current research task exists."
            )

        if current_task.type != "research":

            raise ValueError(
                "Current task is not a research task."
            )




        
        query = (
            current_task.description
            .strip()
        )

        if not query:

            raise ValueError(
                "Research task description cannot be empty."
            )

        started = perf_counter()

        log_event(
            logger,
            level=logging.INFO,
            request_id=request_id,
            event="research_started",
            task_id=current_task.id,
            query=query,
        )





        
        try:

            search_result = (
                await self.research_tool.search(
                    query=query,
                    max_results=MAX_RESEARCH_SOURCES,
                )
            )

        except Exception:

            logger.exception(
                "Research tool execution failed",
                extra={
                    "request_id": request_id,
                    "task_id": current_task.id,
                },
            )

            raise




        

        sources = search_result.get(
            "sources",
            [],
        )

        if not sources:

            raise ValueError(
                "Research returned no sources."
            )




        
        def get_score(
            source,
        ):

            try:

                return float(
                    source.get(
                        "score",
                        0.0,
                    )
                    or 0.0
                )

            except (
                TypeError,
                ValueError,
            ):

                return 0.0

        llm_sources = sorted(
            sources,
            key=get_score,
            reverse=True,
        )[
            :MAX_LLM_SOURCES
        ]




        
        llm_context = (
            self._build_llm_context(
                llm_sources
            )
        )

        if not llm_context:

            raise ValueError(
                "No usable research content was returned."
            )



       

        llm_query = query[
            :MAX_QUERY_CHARS
        ]



       

        prompt = f"""
Research:
{llm_query}

Evidence:
{llm_context}

Create a concise factual synthesis.

Rules:
- Use only the evidence.
- Do not invent facts.
- Do not speculate.
- Summary: maximum {MAX_SUMMARY_WORDS} words.
- Findings: maximum {MAX_KEY_FINDINGS}.
- Each finding: maximum {MAX_FINDING_WORDS} words.
- Do not include sources.
- Do not include URLs.
- Do not repeat findings.

Return only the requested structured output.
"""


       

        try:

            result = (
                await self.structured_llm.ainvoke(
                    prompt
                )
            )

        except Exception:

            logger.exception(
                "Research synthesis failed",
                extra={
                    "request_id": request_id,
                    "task_id": current_task.id,
                },
            )

            raise


        

        summary = str(
            result.summary
        ).strip()

        if not summary:

            raise ValueError(
                "Research result contains an empty summary."
            )



        

        key_findings = (
            self._normalize_findings(
                result.key_findings
            )
        )

        if not key_findings:

            raise ValueError(
                "Research result contains no valid key findings."
            )


        

        research_result = {
            "query": query,
            "summary": summary,
            "key_findings": key_findings,
        }



        
        latency_ms = round(
            (
                perf_counter()
                - started
            )
            * 1000,
            2,
        )


        

        log_event(
            logger,
            level=logging.INFO,
            request_id=request_id,
            event="research_completed",
            task_id=current_task.id,
            searched_source_count=len(
                sources
            ),
            llm_source_count=len(
                llm_sources
            ),
            finding_count=len(
                key_findings
            ),
            latency_ms=latency_ms,
            status="success",
        )

        

        return {
            "research": research_result,
            "task_result": research_result,
        }